In [29]:
#Looking at World Bank Data for generic country information
import json
import requests
import pandas as pd
from pprint import pprint

url = "http://api.worldbank.org/v2/"
api_format = "json"

# Get country information in JSON format
countries_response = requests.get(f"{url}countries?format={api_format}").json()

data = countries_response[1]
#pprint(data)

In [30]:
#Appending Data to Lists to be used in Dataframe

country_name = []
country_capital = []
latitude = []
longitude = []
income_level = []
region = []

for country in data:
    country_name.append(country['name'])
    country_capital.append(country['capitalCity'])
    latitude.append(country['latitude'])
    longitude.append(country['longitude'])
    income_level.append(country['incomeLevel']['value'])
    region.append(country['region']['value'])

In [31]:
#Creating Dataframe with extracted data

country_dict = {
    "Country Name": country_name,
    "Capital City": country_capital,
    "Latitude": latitude,
    "Longitude": longitude,
    "Income Level": income_level,
    "Region": region
}
country_data = pd.DataFrame(country_dict)
country_data

,Country Name,Capital City,Latitude,Longitude,Income Level,Region
0,Aruba,Oranjestad,12.5167,-70.0167,High income,Latin America & Caribbean
1,Africa Eastern and Southern,,,,Aggregates,Aggregates
2,Afghanistan,Kabul,34.5228,69.1761,Low income,South Asia
3,Africa,,,,Aggregates,Aggregates
4,Africa Western and Central,,,,Aggregates,Aggregates
5,Angola,Luanda,-8.81155,13.242,Lower middle income,Sub-Saharan Africa
6,Albania,Tirane,41.3317,19.8172,Upper middle income,Europe & Central Asia
7,Andorra,Andorra la Vella,42.5075,1.5218,High income,Europe & Central Asia
8,Arab World,,,,Aggregates,Aggregates
9,United Arab Emirates,Abu Dhabi,24.4764,54.3705,High income,Middle East & North Africa
10,Argentina,Buenos Aires,-34.6118,-58.4173,Upper middle income,Latin America & Caribbean
11,Armenia,Yerevan,40.1596,44.509,Upper middle income,Europe & Central Asia
12,American Samoa,Pago Pago,-14.2846,-170.691,High income,East Asia & Pacific
13,Antigua and Barbuda,Saint John's,17.1175,-61.8456,High income,Latin America & Caribbean
14,Australia,Canberra,-35.282,149.129,High income,East Asia & Pacific
15,Austria,Vienna,48.2201,16.3798,High income,Europe & Central Asia
16,Azerbaijan,Baku,40.3834,49.8932,Upper middle income,Europe & Central Asia
17,Burundi,Bujumbura,-3.3784,29.3639,Low income,Sub-Saharan Africa
18,East Asia & Pacific (IBRD-only countries),,,,Aggregates,Aggregates
19,Europe & Central Asia (IBRD-only countries),,,,Aggregates,Aggregates
20,Belgium,Brussels,50.8371,4.36761,High income,Europe & Central Asia
21,Benin,Porto-Novo,6.4779,2.6323,Lower middle income,Sub-Saharan Africa
22,Burkina Faso,Ouagadougou,12.3605,-1.53395,Low income,Sub-Saharan Africa
23,Bangladesh,Dhaka,23.7055,90.4113,Lower middle income,South Asia
24,Bulgaria,Sofia,42.7105,23.3238,High income,Europe & Central Asia
25,IBRD countries classified as high income,,,,Aggregates,Aggregates
26,Bahrain,Manama,26.1921,50.5354,High income,Middle East & North Africa
27,"Bahamas, The",Nassau,25.0661,-77.339,High income,Latin America & Caribbean
28,Bosnia and Herzegovina,Sarajevo,43.8607,18.4214,Upper middle income,Europe & Central Asia
29,Latin America & the Caribbean (IBRD-only count...,,,,Aggregates,Aggregates
30,Belarus,Minsk,53.9678,27.5766,Upper middle income,Europe & Central Asia
31,Belize,Belmopan,17.2534,-88.7713,Upper middle income,Latin America & Caribbean
32,Middle East & North Africa (IBRD-only countries),,,,Aggregates,Aggregates
33,Bermuda,Hamilton,32.3293,-64.706,High income,North America
34,Bolivia,La Paz,-13.9908,-66.1936,Lower middle income,Latin America & Caribbean
35,Brazil,Brasilia,-15.7801,-47.9292,Upper middle income,Latin America & Caribbean
36,Barbados,Bridgetown,13.0935,-59.6105,High income,Latin America & Caribbean
37,Brunei Darussalam,Bandar Seri Begawan,4.94199,114.946,High income,East Asia & Pacific
38,Sub-Saharan Africa (IBRD-only countries),,,,Aggregates,Aggregates
39,Bhutan,Thimphu,27.5768,89.6177,Lower middle income,South Asia
40,Botswana,Gaborone,-24.6544,25.9201,Upper middle income,Sub-Saharan Africa
41,Sub-Saharan Africa (IFC classification),,,,Aggregates,Aggregates
42,Central African Republic,Bangui,5.63056,21.6407,Low income,Sub-Saharan Africa
43,Canada,Ottawa,45.4215,-75.6919,High income,North America
44,East Asia and the Pacific (IFC classification),,,,Aggregates,Aggregates
45,Central Europe and the Baltics,,,,Aggregates,Aggregates
46,Europe and Central Asia (IFC classification),,,,Aggregates,Aggregates
47,Switzerland,Bern,46.948,7.44821,High income,Europe & Central Asia
48,Channel Islands,,,,High income,Europe & Central Asia
49,Chile,Santiago,-33.475,-70.6475,High income,Latin America & Caribbean

In [39]:
#Cleaning Dataframe
#Filtering to Countries that are Europe and Central Asia
country_data = country_data.loc[(country_data["Region"] == "Europe & Central Asia") | (country_data["Region"] == "Europe & Central Asia (exlcuding high income)"),:]
country_data

,Country Name,Capital City,Latitude,Longitude,Income Level,Region
6,Albania,Tirane,41.3317,19.8172,Upper middle income,Europe & Central Asia
7,Andorra,Andorra la Vella,42.5075,1.5218,High income,Europe & Central Asia
11,Armenia,Yerevan,40.1596,44.509,Upper middle income,Europe & Central Asia
15,Austria,Vienna,48.2201,16.3798,High income,Europe & Central Asia
16,Azerbaijan,Baku,40.3834,49.8932,Upper middle income,Europe & Central Asia
20,Belgium,Brussels,50.8371,4.36761,High income,Europe & Central Asia
24,Bulgaria,Sofia,42.7105,23.3238,High income,Europe & Central Asia
28,Bosnia and Herzegovina,Sarajevo,43.8607,18.4214,Upper middle income,Europe & Central Asia
30,Belarus,Minsk,53.9678,27.5766,Upper middle income,Europe & Central Asia
47,Switzerland,Bern,46.948,7.44821,High income,Europe & Central Asia
48,Channel Islands,,,,High income,Europe & Central Asia

In [43]:
#Removing Blank Values & Resetting Index - not sure why its not working
country_data = country_data[country_data["Capital City"].notna()]
country_data

,Country Name,Capital City,Latitude,Longitude,Income Level,Region
6,Albania,Tirane,41.3317,19.8172,Upper middle income,Europe & Central Asia
7,Andorra,Andorra la Vella,42.5075,1.5218,High income,Europe & Central Asia
11,Armenia,Yerevan,40.1596,44.509,Upper middle income,Europe & Central Asia
15,Austria,Vienna,48.2201,16.3798,High income,Europe & Central Asia
16,Azerbaijan,Baku,40.3834,49.8932,Upper middle income,Europe & Central Asia
20,Belgium,Brussels,50.8371,4.36761,High income,Europe & Central Asia
24,Bulgaria,Sofia,42.7105,23.3238,High income,Europe & Central Asia
28,Bosnia and Herzegovina,Sarajevo,43.8607,18.4214,Upper middle income,Europe & Central Asia
30,Belarus,Minsk,53.9678,27.5766,Upper middle income,Europe & Central Asia
47,Switzerland,Bern,46.948,7.44821,High income,Europe & Central Asia
48,Channel Islands,,,,High income,Europe & Central Asia